version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always

    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
      - POSTGRES_HOST=db
    ports:
      - "5432:5432"

  cache:
    image: redis:7.0.2-alpine
    restart: always
    environment:
      - REDIS_HOST=cache
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
  app:
    container_name: "app"
    image: faroukhamadi/bankify-backend:latest
    depends_on:
      - db
      - cache
    restart: always
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
      - "4003:4003"
      - "4004:4004"
    volumes:
      - ./server:/usr/src/app/
      - /usr/src/app/node_modules
    environment:
      - WAIT_HOSTS=db:5432
      - REDIS_HOST=cache
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
      - POSTGRES_HOST=db
volumes:
  cache:
    driver: local
