# Typical File for extension: vscode-graphql & CodeGen!
projects:
  default:
    schema:
      - http://localhost:4000/graphql
    documents:
      - "**/*.gql"
    extensions:
      codegen:
        generates:
          ./src/lib/graphql/_kitql/graphqlTypes.ts:
            plugins:
              - typescript
              - typescript-operations
              - typed-document-node
              - typescript-document-nodes

          ./src/lib/graphql/_kitql/graphqlStores.ts:
            plugins:
              - "@kitql/graphql-codegen"
            config:
              importBaseTypesFrom: $lib/graphql/_kitql/graphqlTypes
